//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressWpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Department
    {
        public int Id { get; set; }
        public string DepartmentDep { get; set; }
        public string RegionDep { get; set; }
        public string DistrictRegionDep { get; set; }
        public string DistrictCityDep { get; set; }
        public string CityTypeDep { get; set; }
        public string CityDep { get; set; }
        public string StreetDep { get; set; }
        public string StreetTypeDep { get; set; }
        public string HousDep { get; set; }
        public string PostIndexDep { get; set; }
        public string PartnerDep { get; set; }
        public string StatusDep { get; set; }
        public string RegisterDep { get; set; }
        public string EdrpouDep { get; set; }
        public string AddressDep { get; set; }
        public string PartnerNameDep { get; set; }
        public string IdTerminalDep { get; set; }
        public string KoatuDep { get; set; }
        public string TaxIdDep { get; set; }
        public string Koatu2Dep { get; set; }
    }
}
