//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressWpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Logi
    {
        public int Id { get; set; }
        public string DepartmentLogi { get; set; }
        public string TermialLogi { get; set; }
        public string ModelLogi { get; set; }
        public string SerialNumberLogi { get; set; }
        public string AddressLogi { get; set; }
        public string DataLogLogi { get; set; }
        public string KindLogi { get; set; }
    }
}
