//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressWpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Terminal
    {
        public int Id { get; set; }
        public string DepartmentTerm { get; set; }
        public string TermialTerm { get; set; }
        public string ModelTerm { get; set; }
        public string SerialNumberTerm { get; set; }
        public string DateManufactureTerm { get; set; }
        public string SoftTerm { get; set; }
        public string ProducerTerm { get; set; }
        public string RneRroTerm { get; set; }
        public string SealingTerm { get; set; }
        public string FiscalNumberTerm { get; set; }
        public string OroSerialTerm { get; set; }
        public string OroNumberTerm { get; set; }
        public string TicketSerialTerm { get; set; }
        public string Ticket1sheetTerm { get; set; }
        public string TicketNumberTerm { get; set; }
        public string SendingTerm { get; set; }
        public string BooksArhivTerm { get; set; }
        public string TicketsArhivTerm { get; set; }
        public string ToRroTerm { get; set; }
        public string OwnerRroTerm { get; set; }
        public string RegisterTerm { get; set; }
        public string FinishTerm { get; set; }
    }
}
